name:                blockchain-hs
version:             0.1.0.0
github:              "junjihashimoto/blockchain-hs"
license:             MIT
author:              "Junji Hashimoto"
maintainer:          "junji.hashimoto@gmail.com"
copyright:           "2018 Junji Hashimoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/junjihashimoto/blockchain-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- aeson
- cryptonite
- bytestring

library:
  source-dirs: src

executables:
  blockchain-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain-hs


tests:
  doctest:
    main: doctests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockchain-hs
    - doctest

