/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99. DO NOT MODIFY.
*/
module Sha256_Component
    ( // Inputs
      input signed [63:0] i 


      // Outputs
    , output reg [31:0] \#case_alt  
    );
  wire signed [63:0] ds65;
  wire [31:0] \#case_alt_sel_alt_res ;
  wire [31:0] \#case_alt_sel_alt_res_0 ;
  wire [31:0] \#case_alt_sel_alt_res_1 ;
  wire [31:0] \#case_alt_sel_alt_res_2 ;
  wire [31:0] \#case_alt_sel_alt_res_3 ;
  wire [31:0] \#case_alt_sel_alt_res_4 ;
  wire [31:0] \#case_alt_sel_alt_res_5 ;
  wire [31:0] \#case_alt_sel_alt_res_6 ;
  wire [31:0] \#case_alt_sel_alt_res_7 ;
  wire [31:0] \#case_alt_sel_alt_res_8 ;
  wire [31:0] \#case_alt_sel_alt_res_9 ;
  wire [31:0] \#case_alt_sel_alt_res_10 ;
  wire [31:0] \#case_alt_sel_alt_res_11 ;
  wire [31:0] \#case_alt_sel_alt_res_12 ;
  wire [31:0] \#case_alt_sel_alt_res_13 ;
  wire [31:0] \#case_alt_sel_alt_res_14 ;
  wire [31:0] \#case_alt_sel_alt_res_15 ;
  wire [31:0] \#case_alt_sel_alt_res_16 ;
  wire [31:0] \#case_alt_sel_alt_res_17 ;
  wire [31:0] \#case_alt_sel_alt_res_18 ;
  wire [31:0] \#case_alt_sel_alt_res_19 ;
  wire [31:0] \#case_alt_sel_alt_res_20 ;
  wire [31:0] \#case_alt_sel_alt_res_21 ;
  wire [31:0] \#case_alt_sel_alt_res_22 ;
  wire [31:0] \#case_alt_sel_alt_res_23 ;
  wire [31:0] \#case_alt_sel_alt_res_24 ;
  wire [31:0] \#case_alt_sel_alt_res_25 ;
  wire [31:0] \#case_alt_sel_alt_res_26 ;
  wire [31:0] \#case_alt_sel_alt_res_27 ;
  wire [31:0] \#case_alt_sel_alt_res_28 ;
  wire [31:0] \#case_alt_sel_alt_res_29 ;
  wire [31:0] \#case_alt_sel_alt_res_30 ;
  wire [31:0] \#case_alt_sel_alt_res_31 ;
  wire [31:0] \#case_alt_sel_alt_res_32 ;
  wire [31:0] \#case_alt_sel_alt_res_33 ;
  wire [31:0] \#case_alt_sel_alt_res_34 ;
  wire [31:0] \#case_alt_sel_alt_res_35 ;
  wire [31:0] \#case_alt_sel_alt_res_36 ;
  wire [31:0] \#case_alt_sel_alt_res_37 ;
  wire [31:0] \#case_alt_sel_alt_res_38 ;
  wire [31:0] \#case_alt_sel_alt_res_39 ;
  wire [31:0] \#case_alt_sel_alt_res_40 ;
  wire [31:0] \#case_alt_sel_alt_res_41 ;
  wire [31:0] \#case_alt_sel_alt_res_42 ;
  wire [31:0] \#case_alt_sel_alt_res_43 ;
  wire [31:0] \#case_alt_sel_alt_res_44 ;
  wire [31:0] \#case_alt_sel_alt_res_45 ;
  wire [31:0] \#case_alt_sel_alt_res_46 ;
  wire [31:0] \#case_alt_sel_alt_res_47 ;
  wire [31:0] \#case_alt_sel_alt_res_48 ;
  wire [31:0] \#case_alt_sel_alt_res_49 ;
  wire [31:0] \#case_alt_sel_alt_res_50 ;
  wire [31:0] \#case_alt_sel_alt_res_51 ;
  wire [31:0] \#case_alt_sel_alt_res_52 ;
  wire [31:0] \#case_alt_sel_alt_res_53 ;
  wire [31:0] \#case_alt_sel_alt_res_54 ;
  wire [31:0] \#case_alt_sel_alt_res_55 ;
  wire [31:0] \#case_alt_sel_alt_res_56 ;
  wire [31:0] \#case_alt_sel_alt_res_57 ;
  wire [31:0] \#case_alt_sel_alt_res_58 ;
  wire [31:0] \#case_alt_sel_alt_res_59 ;
  wire [31:0] \#case_alt_sel_alt_res_60 ;
  wire [31:0] \#case_alt_sel_alt_res_61 ;
  wire [31:0] \#case_alt_sel_alt_res_62 ;

  assign \#case_alt_sel_alt_res  = $unsigned(64'd1116352408);

  assign \#case_alt_sel_alt_res_0  = $unsigned(64'd1899447441);

  assign \#case_alt_sel_alt_res_1  = $unsigned(64'd3049323471);

  assign \#case_alt_sel_alt_res_2  = $unsigned(64'd3921009573);

  assign \#case_alt_sel_alt_res_3  = $unsigned(64'd961987163);

  assign \#case_alt_sel_alt_res_4  = $unsigned(64'd1508970993);

  assign \#case_alt_sel_alt_res_5  = $unsigned(64'd2453635748);

  assign \#case_alt_sel_alt_res_6  = $unsigned(64'd2870763221);

  assign \#case_alt_sel_alt_res_7  = $unsigned(64'd3624381080);

  assign \#case_alt_sel_alt_res_8  = $unsigned(64'd310598401);

  assign \#case_alt_sel_alt_res_9  = $unsigned(64'd607225278);

  assign \#case_alt_sel_alt_res_10  = $unsigned(64'd1426881987);

  assign \#case_alt_sel_alt_res_11  = $unsigned(64'd1925078388);

  assign \#case_alt_sel_alt_res_12  = $unsigned(64'd2162078206);

  assign \#case_alt_sel_alt_res_13  = $unsigned(64'd2614888103);

  assign \#case_alt_sel_alt_res_14  = $unsigned(64'd3248222580);

  assign \#case_alt_sel_alt_res_15  = $unsigned(64'd3835390401);

  assign \#case_alt_sel_alt_res_16  = $unsigned(64'd4022224774);

  assign \#case_alt_sel_alt_res_17  = $unsigned(64'd264347078);

  assign \#case_alt_sel_alt_res_18  = $unsigned(64'd604807628);

  assign \#case_alt_sel_alt_res_19  = $unsigned(64'd770255983);

  assign \#case_alt_sel_alt_res_20  = $unsigned(64'd1249150122);

  assign \#case_alt_sel_alt_res_21  = $unsigned(64'd1555081692);

  assign \#case_alt_sel_alt_res_22  = $unsigned(64'd1996064986);

  assign \#case_alt_sel_alt_res_23  = $unsigned(64'd2554220882);

  assign \#case_alt_sel_alt_res_24  = $unsigned(64'd2821834349);

  assign \#case_alt_sel_alt_res_25  = $unsigned(64'd2952996808);

  assign \#case_alt_sel_alt_res_26  = $unsigned(64'd3210313671);

  assign \#case_alt_sel_alt_res_27  = $unsigned(64'd3336571891);

  assign \#case_alt_sel_alt_res_28  = $unsigned(64'd3584528711);

  assign \#case_alt_sel_alt_res_29  = $unsigned(64'd113926993);

  assign \#case_alt_sel_alt_res_30  = $unsigned(64'd338241895);

  assign \#case_alt_sel_alt_res_31  = $unsigned(64'd666307205);

  assign \#case_alt_sel_alt_res_32  = $unsigned(64'd773529912);

  assign \#case_alt_sel_alt_res_33  = $unsigned(64'd1294757372);

  assign \#case_alt_sel_alt_res_34  = $unsigned(64'd1396182291);

  assign \#case_alt_sel_alt_res_35  = $unsigned(64'd1695183700);

  assign \#case_alt_sel_alt_res_36  = $unsigned(64'd1986661051);

  assign \#case_alt_sel_alt_res_37  = $unsigned(64'd2177026350);

  assign \#case_alt_sel_alt_res_38  = $unsigned(64'd2456956037);

  assign \#case_alt_sel_alt_res_39  = $unsigned(64'd2730485921);

  assign \#case_alt_sel_alt_res_40  = $unsigned(64'd2820302411);

  assign \#case_alt_sel_alt_res_41  = $unsigned(64'd3259730800);

  assign \#case_alt_sel_alt_res_42  = $unsigned(64'd3345764771);

  assign \#case_alt_sel_alt_res_43  = $unsigned(64'd3516065817);

  assign \#case_alt_sel_alt_res_44  = $unsigned(64'd3600352804);

  assign \#case_alt_sel_alt_res_45  = $unsigned(64'd4094571909);

  assign \#case_alt_sel_alt_res_46  = $unsigned(64'd275423344);

  assign \#case_alt_sel_alt_res_47  = $unsigned(64'd430227734);

  assign \#case_alt_sel_alt_res_48  = $unsigned(64'd506948616);

  assign \#case_alt_sel_alt_res_49  = $unsigned(64'd659060556);

  assign \#case_alt_sel_alt_res_50  = $unsigned(64'd883997877);

  assign \#case_alt_sel_alt_res_51  = $unsigned(64'd958139571);

  assign \#case_alt_sel_alt_res_52  = $unsigned(64'd1322822218);

  assign \#case_alt_sel_alt_res_53  = $unsigned(64'd1537002063);

  assign \#case_alt_sel_alt_res_54  = $unsigned(64'd1747873779);

  assign \#case_alt_sel_alt_res_55  = $unsigned(64'd1955562222);

  assign \#case_alt_sel_alt_res_56  = $unsigned(64'd2024104815);

  assign \#case_alt_sel_alt_res_57  = $unsigned(64'd2227730452);

  assign \#case_alt_sel_alt_res_58  = $unsigned(64'd2361852424);

  assign \#case_alt_sel_alt_res_59  = $unsigned(64'd2428436474);

  assign \#case_alt_sel_alt_res_60  = $unsigned(64'd2756734187);

  assign \#case_alt_sel_alt_res_61  = $unsigned(64'd3204031479);

  assign \#case_alt_sel_alt_res_62  = $unsigned(64'd3329325298);

  always @(*) begin
    case(ds65)
      64'sd0 : \#case_alt  = \#case_alt_sel_alt_res ;
      64'sd1 : \#case_alt  = \#case_alt_sel_alt_res_0 ;
      64'sd2 : \#case_alt  = \#case_alt_sel_alt_res_1 ;
      64'sd3 : \#case_alt  = \#case_alt_sel_alt_res_2 ;
      64'sd4 : \#case_alt  = \#case_alt_sel_alt_res_3 ;
      64'sd5 : \#case_alt  = \#case_alt_sel_alt_res_4 ;
      64'sd6 : \#case_alt  = \#case_alt_sel_alt_res_5 ;
      64'sd7 : \#case_alt  = \#case_alt_sel_alt_res_6 ;
      64'sd8 : \#case_alt  = \#case_alt_sel_alt_res_7 ;
      64'sd9 : \#case_alt  = \#case_alt_sel_alt_res_8 ;
      64'sd10 : \#case_alt  = \#case_alt_sel_alt_res_9 ;
      64'sd11 : \#case_alt  = \#case_alt_sel_alt_res_10 ;
      64'sd12 : \#case_alt  = \#case_alt_sel_alt_res_11 ;
      64'sd13 : \#case_alt  = \#case_alt_sel_alt_res_12 ;
      64'sd14 : \#case_alt  = \#case_alt_sel_alt_res_13 ;
      64'sd15 : \#case_alt  = \#case_alt_sel_alt_res_14 ;
      64'sd16 : \#case_alt  = \#case_alt_sel_alt_res_15 ;
      64'sd17 : \#case_alt  = \#case_alt_sel_alt_res_16 ;
      64'sd18 : \#case_alt  = \#case_alt_sel_alt_res_17 ;
      64'sd19 : \#case_alt  = \#case_alt_sel_alt_res_18 ;
      64'sd20 : \#case_alt  = \#case_alt_sel_alt_res_19 ;
      64'sd21 : \#case_alt  = \#case_alt_sel_alt_res_20 ;
      64'sd22 : \#case_alt  = \#case_alt_sel_alt_res_21 ;
      64'sd23 : \#case_alt  = \#case_alt_sel_alt_res_22 ;
      64'sd24 : \#case_alt  = \#case_alt_sel_alt_res_23 ;
      64'sd25 : \#case_alt  = \#case_alt_sel_alt_res_24 ;
      64'sd26 : \#case_alt  = \#case_alt_sel_alt_res_25 ;
      64'sd27 : \#case_alt  = \#case_alt_sel_alt_res_26 ;
      64'sd28 : \#case_alt  = \#case_alt_sel_alt_res_27 ;
      64'sd29 : \#case_alt  = \#case_alt_sel_alt_res_28 ;
      64'sd30 : \#case_alt  = \#case_alt_sel_alt_res_29 ;
      64'sd31 : \#case_alt  = \#case_alt_sel_alt_res_30 ;
      64'sd32 : \#case_alt  = \#case_alt_sel_alt_res_31 ;
      64'sd33 : \#case_alt  = \#case_alt_sel_alt_res_32 ;
      64'sd34 : \#case_alt  = \#case_alt_sel_alt_res_33 ;
      64'sd35 : \#case_alt  = \#case_alt_sel_alt_res_34 ;
      64'sd36 : \#case_alt  = \#case_alt_sel_alt_res_35 ;
      64'sd37 : \#case_alt  = \#case_alt_sel_alt_res_36 ;
      64'sd38 : \#case_alt  = \#case_alt_sel_alt_res_37 ;
      64'sd39 : \#case_alt  = \#case_alt_sel_alt_res_38 ;
      64'sd40 : \#case_alt  = \#case_alt_sel_alt_res_39 ;
      64'sd41 : \#case_alt  = \#case_alt_sel_alt_res_40 ;
      64'sd42 : \#case_alt  = \#case_alt_sel_alt_res_41 ;
      64'sd43 : \#case_alt  = \#case_alt_sel_alt_res_42 ;
      64'sd44 : \#case_alt  = \#case_alt_sel_alt_res_43 ;
      64'sd45 : \#case_alt  = \#case_alt_sel_alt_res_44 ;
      64'sd46 : \#case_alt  = \#case_alt_sel_alt_res_45 ;
      64'sd47 : \#case_alt  = \#case_alt_sel_alt_res_46 ;
      64'sd48 : \#case_alt  = \#case_alt_sel_alt_res_47 ;
      64'sd49 : \#case_alt  = \#case_alt_sel_alt_res_48 ;
      64'sd50 : \#case_alt  = \#case_alt_sel_alt_res_49 ;
      64'sd51 : \#case_alt  = \#case_alt_sel_alt_res_50 ;
      64'sd52 : \#case_alt  = \#case_alt_sel_alt_res_51 ;
      64'sd53 : \#case_alt  = \#case_alt_sel_alt_res_52 ;
      64'sd54 : \#case_alt  = \#case_alt_sel_alt_res_53 ;
      64'sd55 : \#case_alt  = \#case_alt_sel_alt_res_54 ;
      64'sd56 : \#case_alt  = \#case_alt_sel_alt_res_55 ;
      64'sd57 : \#case_alt  = \#case_alt_sel_alt_res_56 ;
      64'sd58 : \#case_alt  = \#case_alt_sel_alt_res_57 ;
      64'sd59 : \#case_alt  = \#case_alt_sel_alt_res_58 ;
      64'sd60 : \#case_alt  = \#case_alt_sel_alt_res_59 ;
      64'sd61 : \#case_alt  = \#case_alt_sel_alt_res_60 ;
      64'sd62 : \#case_alt  = \#case_alt_sel_alt_res_61 ;
      64'sd63 : \#case_alt  = \#case_alt_sel_alt_res_62 ;
      default : \#case_alt  = {32 {1'bx}};
    endcase
  end

  assign ds65 = i;
endmodule

