/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99. DO NOT MODIFY.
*/
module Sha256_Component_0
    ( // Inputs
      input [2047:0] ds 
    , input signed [63:0] i 

      // Outputs
    , output reg [31:0] \#case_alt  
    );
  wire [31:0] ds1;
  wire [31:0] ds2;
  wire [31:0] ds3;
  wire [31:0] ds4;
  wire [31:0] ds5;
  wire [31:0] ds6;
  wire [31:0] ds7;
  wire [31:0] ds8;
  wire [31:0] ds9;
  wire [31:0] ds10;
  wire [31:0] ds11;
  wire [31:0] ds12;
  wire [31:0] ds13;
  wire [31:0] ds14;
  wire [31:0] ds15;
  wire [31:0] ds16;
  wire [31:0] ds17;
  wire [31:0] ds18;
  wire [31:0] ds19;
  wire [31:0] ds20;
  wire [31:0] ds21;
  wire [31:0] ds22;
  wire [31:0] ds23;
  wire [31:0] ds24;
  wire [31:0] ds25;
  wire [31:0] ds26;
  wire [31:0] ds27;
  wire [31:0] ds28;
  wire [31:0] ds29;
  wire [31:0] ds30;
  wire [31:0] ds31;
  wire [31:0] ds32;
  wire [31:0] ds33;
  wire [31:0] ds34;
  wire [31:0] ds35;
  wire [31:0] ds36;
  wire [31:0] ds37;
  wire [31:0] ds38;
  wire [31:0] ds39;
  wire [31:0] ds40;
  wire [31:0] ds41;
  wire [31:0] ds42;
  wire [31:0] ds43;
  wire [31:0] ds44;
  wire [31:0] ds45;
  wire [31:0] ds46;
  wire [31:0] ds47;
  wire [31:0] ds48;
  wire [31:0] ds49;
  wire [31:0] ds50;
  wire [31:0] ds51;
  wire [31:0] ds52;
  wire [31:0] ds53;
  wire [31:0] ds54;
  wire [31:0] ds55;
  wire [31:0] ds56;
  wire [31:0] ds57;
  wire [31:0] ds58;
  wire [31:0] ds59;
  wire [31:0] ds60;
  wire [31:0] ds61;
  wire [31:0] ds62;
  wire [31:0] ds63;
  wire [31:0] ds64;
  wire signed [63:0] ds65;

  assign ds1 = ds[2047:2016];

  assign ds2 = ds[2015:1984];

  assign ds3 = ds[1983:1952];

  assign ds4 = ds[1951:1920];

  assign ds5 = ds[1919:1888];

  assign ds6 = ds[1887:1856];

  assign ds7 = ds[1855:1824];

  assign ds8 = ds[1823:1792];

  assign ds9 = ds[1791:1760];

  assign ds10 = ds[1759:1728];

  assign ds11 = ds[1727:1696];

  assign ds12 = ds[1695:1664];

  assign ds13 = ds[1663:1632];

  assign ds14 = ds[1631:1600];

  assign ds15 = ds[1599:1568];

  assign ds16 = ds[1567:1536];

  assign ds17 = ds[1535:1504];

  assign ds18 = ds[1503:1472];

  assign ds19 = ds[1471:1440];

  assign ds20 = ds[1439:1408];

  assign ds21 = ds[1407:1376];

  assign ds22 = ds[1375:1344];

  assign ds23 = ds[1343:1312];

  assign ds24 = ds[1311:1280];

  assign ds25 = ds[1279:1248];

  assign ds26 = ds[1247:1216];

  assign ds27 = ds[1215:1184];

  assign ds28 = ds[1183:1152];

  assign ds29 = ds[1151:1120];

  assign ds30 = ds[1119:1088];

  assign ds31 = ds[1087:1056];

  assign ds32 = ds[1055:1024];

  assign ds33 = ds[1023:992];

  assign ds34 = ds[991:960];

  assign ds35 = ds[959:928];

  assign ds36 = ds[927:896];

  assign ds37 = ds[895:864];

  assign ds38 = ds[863:832];

  assign ds39 = ds[831:800];

  assign ds40 = ds[799:768];

  assign ds41 = ds[767:736];

  assign ds42 = ds[735:704];

  assign ds43 = ds[703:672];

  assign ds44 = ds[671:640];

  assign ds45 = ds[639:608];

  assign ds46 = ds[607:576];

  assign ds47 = ds[575:544];

  assign ds48 = ds[543:512];

  assign ds49 = ds[511:480];

  assign ds50 = ds[479:448];

  assign ds51 = ds[447:416];

  assign ds52 = ds[415:384];

  assign ds53 = ds[383:352];

  assign ds54 = ds[351:320];

  assign ds55 = ds[319:288];

  assign ds56 = ds[287:256];

  assign ds57 = ds[255:224];

  assign ds58 = ds[223:192];

  assign ds59 = ds[191:160];

  assign ds60 = ds[159:128];

  assign ds61 = ds[127:96];

  assign ds62 = ds[95:64];

  assign ds63 = ds[63:32];

  assign ds64 = ds[31:0];

  always @(*) begin
    case(ds65)
      64'sd0 : \#case_alt  = ds1;
      64'sd1 : \#case_alt  = ds2;
      64'sd2 : \#case_alt  = ds3;
      64'sd3 : \#case_alt  = ds4;
      64'sd4 : \#case_alt  = ds5;
      64'sd5 : \#case_alt  = ds6;
      64'sd6 : \#case_alt  = ds7;
      64'sd7 : \#case_alt  = ds8;
      64'sd8 : \#case_alt  = ds9;
      64'sd9 : \#case_alt  = ds10;
      64'sd10 : \#case_alt  = ds11;
      64'sd11 : \#case_alt  = ds12;
      64'sd12 : \#case_alt  = ds13;
      64'sd13 : \#case_alt  = ds14;
      64'sd14 : \#case_alt  = ds15;
      64'sd15 : \#case_alt  = ds16;
      64'sd16 : \#case_alt  = ds17;
      64'sd17 : \#case_alt  = ds18;
      64'sd18 : \#case_alt  = ds19;
      64'sd19 : \#case_alt  = ds20;
      64'sd20 : \#case_alt  = ds21;
      64'sd21 : \#case_alt  = ds22;
      64'sd22 : \#case_alt  = ds23;
      64'sd23 : \#case_alt  = ds24;
      64'sd24 : \#case_alt  = ds25;
      64'sd25 : \#case_alt  = ds26;
      64'sd26 : \#case_alt  = ds27;
      64'sd27 : \#case_alt  = ds28;
      64'sd28 : \#case_alt  = ds29;
      64'sd29 : \#case_alt  = ds30;
      64'sd30 : \#case_alt  = ds31;
      64'sd31 : \#case_alt  = ds32;
      64'sd32 : \#case_alt  = ds33;
      64'sd33 : \#case_alt  = ds34;
      64'sd34 : \#case_alt  = ds35;
      64'sd35 : \#case_alt  = ds36;
      64'sd36 : \#case_alt  = ds37;
      64'sd37 : \#case_alt  = ds38;
      64'sd38 : \#case_alt  = ds39;
      64'sd39 : \#case_alt  = ds40;
      64'sd40 : \#case_alt  = ds41;
      64'sd41 : \#case_alt  = ds42;
      64'sd42 : \#case_alt  = ds43;
      64'sd43 : \#case_alt  = ds44;
      64'sd44 : \#case_alt  = ds45;
      64'sd45 : \#case_alt  = ds46;
      64'sd46 : \#case_alt  = ds47;
      64'sd47 : \#case_alt  = ds48;
      64'sd48 : \#case_alt  = ds49;
      64'sd49 : \#case_alt  = ds50;
      64'sd50 : \#case_alt  = ds51;
      64'sd51 : \#case_alt  = ds52;
      64'sd52 : \#case_alt  = ds53;
      64'sd53 : \#case_alt  = ds54;
      64'sd54 : \#case_alt  = ds55;
      64'sd55 : \#case_alt  = ds56;
      64'sd56 : \#case_alt  = ds57;
      64'sd57 : \#case_alt  = ds58;
      64'sd58 : \#case_alt  = ds59;
      64'sd59 : \#case_alt  = ds60;
      64'sd60 : \#case_alt  = ds61;
      64'sd61 : \#case_alt  = ds62;
      64'sd62 : \#case_alt  = ds63;
      64'sd63 : \#case_alt  = ds64;
      default : \#case_alt  = {32 {1'bx}};
    endcase
  end

  assign ds65 = i;
endmodule

